Repository prgrms-web-devcourse-final-project/WEB5_6_LuckyVicky_FE, pull requests merged in 2025-09, with the labels that each got.

#13 Feat/funding
  src/app/funding/[id]/page.tsx
  src/app/funding/page.tsx
  src/assets/icon/empty_heart.svg
  src/assets/icon/full_heart.svg
  src/assets/icon/leftArrow.svg
  src/assets/icon/rightArrow.svg
  src/components/funding/FundingCard.tsx
  src/img/exampleImg.png
Labels: 🎨 design

#14 [feat] 로그인, 회원가입 페이지 퍼블리싱 마무리
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/page.tsx
  src/assets/icon/checkbox_false.svg
  src/assets/icon/checkbox_true.svg
  src/assets/icon/google.png
  src/assets/icon/kakao.png
  src/assets/icon/success.svg
  src/assets/icon/x.svg
  src/components/Modal.tsx
  src/components/ToastProvider.tsx
  src/components/register/SignupButton.tsx
  src/utils/validators.ts
Labels: ✨ feature, 🎨 design

#16 [feat] 공지사항/FAQ UI 구현, 회원가입/로그인 api 연동
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/funding/[id]/page.tsx
  src/app/funding/page.tsx
  src/app/help/faq/page.tsx
  src/app/help/layout.tsx
  src/app/help/notice/page.tsx
  src/components/help/HelpSidebar.tsx
  src/components/table/DataTable.tsx
  src/services/auth.ts
Labels: ✨ feature, 🎨 design

#26 [chore] 폴더 구조 변경
  src/app/(site)/(auth)/layout.tsx
  src/app/(site)/(auth)/login/page.tsx
  src/app/(site)/(auth)/password/page.tsx
  src/app/(site)/(auth)/register/page.tsx
  src/app/(site)/(auth)/register/terms.ts
  src/app/(site)/category/[slug]/layout.tsx
  src/app/(site)/category/[slug]/page.tsx
  src/app/(site)/fonts/SUIT-Variable.woff2
  src/app/(site)/funding/[id]/page.tsx
  src/app/(site)/funding/page.tsx
  src/app/(site)/help/contact/[id]/page.tsx
  src/app/(site)/help/contact/new/page.tsx
  src/app/(site)/help/contact/page.tsx
  src/app/(site)/help/faq/[id]/page.tsx
  src/app/(site)/help/faq/page.tsx
  src/app/(site)/help/layout.tsx
  src/app/(site)/help/notice/[id]/page.tsx
  src/app/(site)/help/notice/new/page.tsx
  src/app/(site)/help/notice/page.tsx
  src/app/(site)/layout.tsx
  src/app/(site)/order/complete/page.tsx
  src/app/(site)/order/page.tsx
  src/app/(site)/order/payment/page.tsx
  src/app/(site)/order/stores/orderStore.ts
  src/app/(site)/page.tsx
  src/app/(site)/product/[id]/page.tsx
  src/app/admin/layout.tsx
  src/app/admin/login/page.tsx
  src/app/layout.tsx
  src/components/ToastProvider.tsx
  src/middleware.ts
Labels: chore

#30 [ui] 검색결과 페이지
  src/app/(site)/product/[id]/page.tsx
  src/app/(site)/search/page.tsx
  src/assets/icon/error.svg
  src/components/Header.tsx
  src/components/productDetail/ReviewInfo.tsx
  src/components/search/ResultHeader.tsx
  src/components/search/SearchBox.tsx
  src/utils/search.ts
Labels: ✨ feature, 🎨 design
